version: "3"
services:
  app:
    container_name: auth-server
    restart: always
    build: ./auth
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - auth_data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-notifications
    restart: always
    build: ./api
    ports:
      - "8000:8000"
volumes:
  auth_data: